/** 用 esbuild 打包 smoke-adapter.mjs（解析 @ 别名 + 注入 import.meta.env）后执行。 */
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const root = fileURLToPath(new URL('..', import.meta.url))
const outfile = join(tmpdir(), 'yinsuo-smoke.mjs')
const env = JSON.stringify({ VITE_DATA_SOURCE: 'mock', VITE_API_BASE_URL: '/api/v1', MODE: 'production' })

execFileSync('npx', ['esbuild', 'scripts/smoke-adapter.mjs', '--bundle', '--format=esm', '--platform=node',
  '--target=node18', `--outfile=${outfile}`, `--alias:@=${join(root, 'src')}`, `--define:import.meta.env=${env}`,
  '--log-level=warning'], { cwd: root, stdio: 'inherit' })

writeFileSync(outfile + '.note', 'generated by scripts/build-smoke.mjs')
execFileSync(process.execPath, [outfile], { cwd: root, stdio: 'inherit' })
